const Categories = [
  "Art & Collectibles",
  "Automotive",
  "Baby & Kids",
  "Beauty & Personal Care",
  "Books & Magazines",
  "Clothing & Accessories",
  "Electronics",
  "Health",
  "Home & Kitchen",
  "Food & Beverages",
  "Furniture",
  "Garden & Outdoor",
  "Health & Fitness",
  "Jewelry & Watches",
  "Musical Instruments",
  "Office Supplies",
  "Pet Supplies",
  "Scientific Equipment",
  "Sports & Outdoors",
  "Tools & Home Improvement",
  "Toys & Games",
];

export default Categories;
